<?php
// FROM HASH: dd9bc1ac92405f0ea0ff0ddf59b23d34
return array('macros' => array(), 'code' => function($__templater, array $__vars)
{
	$__finalCompiled = '';
	$__finalCompiled .= '<p>Cảm ơn bạn đã ghé thăm www.codevn.net. Mong bạn vui lòng đọc các điều khoản và điều kiện trong phần này một cách kỹ lưỡng vì khi bạn sử dụng trang web này nghĩa là bạn đã chấp nhận các Điều khoản và Điều kiện được ghi ở đây.</p>
<p>Trang web này được điều hành bởi BuiDoi Group (tức BuiDoi.Net). Trong trang web, các thuật ngữ "chúng tôi", "của chúng tôi", "CodeVN" và "BuiDoi" đều ám chỉ CodeVn.Net. "bạn" là từ ám chỉ bất cứ ai truy cập và/hoặc sử dụng trang web này.</p>
<p><strong>Thông báo bảo mật của trang web</strong></p>
<p>Chúng tôi chỉ thu thập những thông tin bạn đồng ý cung cấp hoặc những thông tin đó cần để cung cấp (hoặc cải thiện) các dịch vụ của chúng tôi. Các thông tin được thu thập bao gồm các thông tin trực tiếp như tên, địa chỉ và địa chỉ e-mail và các thông tin gián tiếp như cookies, kết nối và thông tin hệ thống.</p>
<p>Bạn có thể gửi cho chúng tôi địa chỉ e-mail, tên, số điện thoại của bạn, v.v. để chúng tôi có thể cung cấp cho bạn thông tin về các dịch vụ của CodeVn.Net, mời các bạn tham gia các cuộc thi hoặc khảo sát của chúng tôi.</p>
<p>Bạn có thể yên tâm rằng chúng tôi sẽ áp dụng tất cả các biện pháp cần thiết để lưu giữ các thông tin cá nhân của bạn được bảo mật và an toàn.</p>
<p>Mặc dù chúng tôi cố gắng để đảm bảo độ chính xác và đầy đủ của thông tin trên trang web này, <strong>chúng tôi không chịu trách nhiệm nếu thông tin chúng tôi công bố trên trang web là không chính xác hoặc không đầy đủ</strong>. bạn cần chấp nhận rủi ro khi hoàn toàn tin cậy vào các tài liệu trên trang web này, đó là rủi ro của riêng bạn. Bạn đồng ý rằng trách nhiệm của bạn là giám sát bất kỳ thay đổi nào về tài liệu và thông tin có trên trang web.</p>
<p><strong>Sự truyền thông tin</strong></p>
<p>Mọi giao tiếp không phải là cá nhân hay tài liệu bạn email đến trang web này bao gồm bất cứ dữ liệu, câu hỏi, nhận xét, đề nghị nào hoặc những thứ tương tự sẽ được xem như những thông tin không bảo mật và không độc quyền. Bất cứ thứ gì bạn truyền hoặc đăng lên đều trở thành tài sản của CodeVn.Net và có thể được sử dụng cho bất cứ mục đích nào, bao gồm và không giới hạn việc nhân bản, công khai thông tin, truyền dữ liệu, xuất bản, phát sóng và đăng tin. Hơn nữa, CodeVn.Net còn được sử dụng các ý tưởng, bản thiết kế, phát minh, triển khai, đề nghị hay quan điểm bạn gửi cho trang web cho bất cứ mục đích nào (bao gồm nhưng không giới hạn việc phát triển, sản xuất, quảng cáo và marketing sản phẩm). Mọi sự sử dụng nói trên sẽ không có bồi thường nào cho phía đã đăng thông tin. Khi bạn gửi thông tin lên trang web cũng có nghĩa là bạn đang bảo đảm rằng bạn sở hữu các tài liệu / nội dung đã gửi, rằng chúng không bêu xấu và việc sử dụng thông tin đó của CodeVn.Net sẽ không vi phạm quyền của bên thứ ba hoặc không vi phạm pháp luật. CodeVn.Net cũng không có nghĩa vụ phải sử dụng thông tin đã gửi.</p>
<p><strong>Quyền sở hữu trí tuệ</strong></p>
<p>Tất cả quyền tác giả và các quyền sở hữu trí tuệ về câu chữ, hình ảnh và tài liệu trên trang web này là tài sản của CodeVn.Net hoặc đã được cho phép của chủ sở hữu liên quan.</p>
<p>Bạn được phép duyệt trang web này, sao chép lại bằng cách in, hoặc ghi vào một đĩa cứng để đưa cho những người khác. Việc này chỉ được làm với điều kiện bạn giữ nguyên các thông báo về bản quyền và độc quyền, và tên thương mại nói trên phải xuất hiện trên bản sao đó. Không sao chép bất kỳ phần nào của trang web này để đem bán hoặc phân phối vì lợi ích thương mại, cũng không được sửa hoặc kết hợp làm với bất kể việc gì, xuất bản hoặc làm trang web.</p>
<p>Thương hiệu, biểu tượng, ký tự và nhãn hiệu dịch vụ (gọi chung là "Thương hiệu") hiển thị trên trang web này thuộc về CodeVn.Net. Không có nội dung nào trên trang web này được hiểu là cấp phép hoặc quyền sử dụng nhãn hiệu hàng hoá hiển thị trên trang web này. Việc bạn sử dụng / dùng nhầm các Thương hiệu trên trang web này, hoặc bất kỳ nội dung nào trên trang web này, ngoại trừ theo quy định tại các Điều khoản và Điều kiện, đều bị nghiêm cấm. CodeVn.Net sẽ kiên quyết bảo vệ quyền sở hữu trí tuệ của mình hết mức trước mọi điều khoản của pháp luật.</p>
<p><strong>Liên kết với các trang web khác</strong></p>
<p>Các đường link trên các trang web của CodeVn.Net có thể đưa bạn ra ngoài mạng lưới và hệ thống của CodeVn.Net và CodeVn.Net không chịu trách nhiệm về tính chính xác, nội dung hoặc chức năng của các trang web thuộc bên thứ ba. Các đường link được cung cấp với thiện ý nhưng CodeVn.Net không thể chịu trách nhiệm cho bất kỳ thay đổi sau đó của các trang web thuộc bên thứ ba khác mà chúng tôi cung cấp đường link. Việc cung cấp các đường link này không có nghĩa là CodeVn.Net đã chứng thực chúng. Chúng tôi khuyên bạn nên tự nhận thức được và đọc cẩn thận tất cả các thông báo về luật pháp và bảo mật của tất cả các trang web bạn truy cập.</p>
<p><strong>Bảo đảm và từ chối</strong></p>
<p>Việc sử dụng trang web này là quyết định của bạn và bạn phải chấp nhận mọi rủi ro của nó.</p>
<p><strong>Những đảm bảo</strong></p>
<p>Trang web này được phát triển trên quan điểm “nó là như thế” và “như nó đã có” và do đó, CodeVn.Net không bảo đảm dưới bất kỳ hình thức nào về cách thể hiện, các ngụ ý, luật định (kể cả sự bảo đảm mang ngụ ý thương mại hay về chất lượng hoặc sự phù hợp vì một mục đích cụ thể nào đó) hoặc mặt khác bảo đảm hay phản đối rằng các tài liệu trên trang web này là đầy đủ, chính xác, đáng tin cậy, kịp thời, không xâm phạm các bên thứ ba, rằng truy cập vào trang web này sẽ không bị gián đoạn hoặc không bị nhiễm virus, rằng trang web này là an toàn, rằng bất kỳ lời khuyên hay ý kiến nào của CodeVn.Net trên trang web này là chính xác hoặc để làm căn cứ đúng đắn và bất cứ sự phản đối hay đảm bảo nào cũng được miễn trừ trách nhiệm.</p>
<p>Xin lưu ý rằng tại một số địa phương, pháp lý có thể không cho phép loại trừ các bảo đảm ngụ ý đó, vì vậy, một số các loại trừ có thể không đúng với bạn. Xin vui lòng kiểm tra lại luật pháp tại nơi bạn sống.</p>
<p>Chúng tôi có quyền hạn chế, đình chỉ hoặc chấm dứt các truy cập của bạn vào trang web này mà không cần thông báo hoặc hạn chế, đình chỉ hoặc chấm dứt bất kỳ tính năng nào của trang web hay bất kỳ tính năng hay một phần những điều đó bất cứ lúc nào.</p>
<p><strong>Nghĩa vụ pháp lý</strong></p>
<p>CodeVn.Net và/hoặc các đơn vị thay mặt chúng tôi tạo ra, phát triển, cung cấp trang web này sẽ không có trách nhiệm pháp lý hoặc trách nhiệm về bất cứ điều gì dù là trực tiếp, ngẫu nhiên, hậu quả, gián tiếp, đặc biệt hoặc các hỏng hóc gây thiệt hại, chi phí, tổn thất hoặc trách nhiệm pháp lý về bất cứ thứ gì và bằng bất cứ cách nào phát sinh từ việc bạn truy cập, sử dụng, không có khả năng sử dụng, thay đổi nội dung trang web hoặc phát sinh từ bất kỳ trang web nào bạn truy cập thông qua một liên kết từ trang web này hoặc từ bất kỳ việc gì chúng tôi làm hoặc không làm được do hậu quả của các thư điện tử bạn gửi cho chúng tôi, trong phạm vi cho phép của pháp luật hiện hành.</p>
<p>CodeVn.Net và/hoặc đơn vị khác tham gia vào việc tạo ra, phát triển hay cung cấp trang web này không chịu trách nhiệm duy trì các tài liệu và dịch vụ đăng trên trang web hoặc làm bất cứ việc gì để sữa chữa, cập nhật hay thông báo với những nội dung này. Bất cứ tài liệu nào trên trang web này cũng có thể được thay đổi không cần báo trước.</p>
<p>Ngoài ra, CodeVn.Net sẽ không chịu trách nhiệm pháp lý hay trách nhiệm về bất cứ điều gì dẫn đến tổn thất do virus và gây hư hại cho máy tính hay các tài sản khác của bạn khi bạn sử dụng, truy cập hay tải xuống các tài liệu từ trang web này. Nếu bạn lựa chọn tải xuống tài liệu từ trang web này, bạn cần chấp nhận mọi rủi ro do việc đó mang lại.</p>
<p>Trong phạm vi tối đa cho phép theo quy định của luật hiện hành, bạn đã từ bỏ tất cả các khiếu nại chống lại CodeVn.Net, cán bộ, giám đốc, nhân viên, nhà cung cấp và lập trình viên của CodeVn.Net về những việc xảy ra khi bạn sử dụng hoặc truy cập trang web này.</p>
<p><strong>Những hành vi bị cấm</strong></p>
<p>Bạn bị cấm không được làm bất cứ điều gì trên trang trang web này mà CodeVn.Net xem xét thấy rằng không phù hợp và/hoặc cho là hành động vi phạm pháp luật hay bị cấm bởi pháp luật hiện hành. Những hành động đó bao gồm nhưng không giới hạn ở:</p>
<p>1.	Bất cứ hành động nào vi phạm sự riêng tư (bao gồm tải lên các thông tin cá nhân mà không được sự đồng ý) hay bất cứ hành động động nào vi phạm quyền cá nhân;</p>
<p>2.	Sử dụng trang web này để bôi nhọ hoặc phỉ báng CodeVn.Net và các nhân viên của CodeVn.Net hoặc những người khác hoặc hành động gây tiếng xấu cho CodeVn.Net;</p>
<p>3.	Tải lên những tài liệu có chứa virus và có thể dẫn đến hư hại tài sản của CodeVn.Net hoặc tài sản của những người khác; và đăng hoặc truyền lên trang web này các tài liệu không được ủy quyền bao gồm nhưng không giới hạn tài liệu, theo ý kiến của chúng tôi, gây khó chịu, gây thiệt hại cho hoặc vi phạm hệ thống của CodeVn.Net hoặc của bên thứ ba hay cho an ninh mạng, phỉ báng, phân biệt chủng tộc, khiêu dâm, đe dọa hay bất hợp pháp.</p>
<p><strong>Thẩm quyền và luật điều chỉnh</strong></p>
<p>CodeVn.Net không trình bày rằng các tài liệu và thông tin trên trang web này là phù hợp và sẵn có ở mọi quốc gia hay mọi ngôn ngữ.</p>
<p>Bạn và CodeVn.Net đồng ý rằng bất kỳ tranh cãi hoặc khiếu nại nào phát sinh từ hoặc liên quan đến việc sử dụng trang web này sẽ được giải quyết theo pháp luật Việt Nam.</p>
<p><strong>Cookies</strong></p>
<p>CodeVn.Net có sử dụng công nghệ theo dấu ("cookies"). Chính sách của CodeVn.Net về sử dụng cookie đã được ghi ở phần chính sách bảo mật về thông tin cá nhân của CodeVn.Net trong trang này.</p>
<p><strong>Cập nhật các thông báo pháp lý</strong></p>
<p>Chúng tôi có toàn quyền thay đổi hay sửa chữa thông báo này. Xin vui lòng đọc các trang này thường xuyên để biết các thay đổi và bổ sung thông tin đó.</p>
<p><strong>Bản quyền</strong> Copyright 2010 © CodeVn.Net</p>';
	return $__finalCompiled;
});