<?php
return array (
  'admin_permission.addOn' => 'Quản lý Tiện ích',
  'admin_permission.advertising' => 'Quản lý quảng cáo',
  'admin_permission.attachment' => 'Quản lý tập tin đính kèm',
  'admin_permission.ban' => 'Quản lý các lệnh cấm',
  'admin_permission.bbCodeSmilie' => 'Manage BB codes and smilies',
  'admin_permission.cron' => 'Quản lý mục Cron',
  'admin_permission.help' => 'Quản lý trợ giúp',
  'admin_permission.import' => 'Nhập dữ liệu',
  'admin_permission.language' => 'Quản lý ngôn ngữ và cụm từ',
  'admin_permission.navigation' => 'Quản lý điều hướng',
  'admin_permission.node' => 'Quản lý chuyên mục',
  'admin_permission.notice' => 'Quản lý thông báo',
  'admin_permission.option' => 'Quản lý tùy chọn',
  'admin_permission.payment' => 'Quản lý các nhà cung cấp dịch vụ',
  'admin_permission.rebuildCache' => 'Cập nhật bộ nhớ đệm',
  'admin_permission.style' => 'Quản lý giao diện, thuộc tính giao diện và mẫu',
  'admin_permission.tags' => 'Quản lý từ khóa',
  'admin_permission.thread' => 'Quản lý chủ đề và bài viết',
  'admin_permission.trophy' => 'Quản lý danh hiệu',
  'admin_permission.user' => 'Quản lý thành viên và Kiểm duyệt viên',
  'admin_permission.userField' => 'Quản lý trường tùy chỉnh thành viên',
  'admin_permission.userGroup' => 'Quản lý Nhóm thành viên',
  'admin_permission.userUpgrade' => 'Quản lý nâng cấp thành viên',
  'admin_permission.viewLogs' => 'Xem nhật ký',
  'admin_permission.viewStatistics' => 'Xem số liệu thống kê',
  'admin_permission.warning' => 'Quản lý cảnh cáo',
  'admin_permission.widget' => 'Quản lý widget',
);